### ISSUE TITLE
希望能针对docker-compose进行一下优化

### ISSUE THREAD

**Issue by tHaxWLa** [shanmiteko/LotteryAutoScript#108]
### 描述

比如合并为同一个容器,定时运行

这个是我改的多容器yml
```
version: '3'

services:

  shanmite-lottery-update:
    image: shanmite/lottery_auto_docker
    container_name: update
    restart: unless-stopped
    volumes:
      - ./env.js:/lottery/env.js
      - ./my_config.js:/lottery/my_config.js
    command: ["update"]
    extra_hosts:
      - "gitee.com:154.213.2.253"
      - "github.com:140.82.113.4"
      - "raw.githubusercontent.com:185.199.108.133"

  shanmite-lottery-start:
    image: shanmite/lottery_auto_docker
    container_name: start
    restart: unless-stopped
    volumes:
      - ./env.js:/lottery/env.js
      - ./my_config.js:/lottery/my_config.js
    command: ["start"]

  shanmite-lottery-check:
    image: shanmite/lottery_auto_docker
    container_name: check
    restart: unless-stopped
    volumes:
      - ./env.js:/lottery/env.js
      - ./my_config.js:/lottery/my_config.js
    command: ["check"]

  shanmite-lottery-clear:
    image: shanmite/lottery_auto_docker
    container_name: clear
    restart: unless-stopped
    volumes:
      - ./env.js:/lottery/env.js
      - ./my_config.js:/lottery/my_config.js
    command: ["clear"]
```
